CREATE DATABASE websocket;
USE websocket;

CREATE TABLE sensor(
	MQ2 FLOAT,
	MQ3 FLOAT,
	MQ5 FLOAT,
	MQ8 FLOAT,
	MQ135 FLOAT,
	HORA TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

SELECT * FROM sensor;

#DELETE FROM sensor;
#DROP DATABASE websocket;
